###
http://localhost:3000

###
http://localhost:4000/login

###
http://localhost:4000/.well-known/jwks.json

###
http://localhost:3000/protected
Authorization:  Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImR1bW15VXNlciIsImlhdCI6MTcxNDMxNjgwOCwiZXhwIjoxNzE0MzE3NDA4fQ.DGLQkxo7BTe8suvf85wXa-kF5_sXuADpmNghNu_AtZ-XwATBXtFo-DIXL0A0RD0vM9KNmYOZZCHS_CJZaHyhyi4lXc0CTghng36-P2wJy8oUzJdRmxfobTYtj1mKb_7ynab5-5RHmZOjibD5maZLGDMUgJdvSO8mmtSoeJ64WHU18NdZo-vWduJy0D6vilx-gIXmhn0HSA_KQkijmVUsG6TJKwZrgmosoj4XyW3R1Juj4nvs9Hp0g2owGOfDIy05yNuwYcldW-KAtA-GnYmzrNaDxhNIvSUg6aik_xH4wktxgi6O7m8GWSP_un1xo1YZUZmed9bnO1bTiphSU2G3b6LdrU3K8iffVkz_TpvOuQyLyi7mavxosKNCTkq8fQzpy98G2qDfBkbZZsg2mVhbrEZ46ikky-jV_n5f3DeIHnvGd_NS-eQfEu3RkZa1Kle2WjZu7_MHpAJwb5ifTC3_27UQ-pSpkVZ_cppbFovnVucbbfVrEv5YuK0Npjxjkj_EhyGemAvfk5hjHAL-cCbS9TecAqiKpG-j4q0vYvoMYc-tm1SnOBaoECgAoWSvxP96zQ-KkXRnJtPUAjQ3QLnnlpo1NyyWsWrzbN7keYf0lxHvWGdHENEmUCJfa8BMsAPWi9fVvdfyNXTL1Zwj4-JvMIqu5bmjwlPYpRJD0VRPQWU